#!/bin/bash
clear
software () {
	# Array of required flatpaks
	required_flatpaks=(
	"app.drey.Warp"
	"chat.revolt.RevoltDesktop"
	"com.belmoussaoui.Authenticator"
	"com.bitwarden.desktop"
	"com.brave.Browser"
	"com.dec05eba.gpu_screen_recorder"
	"com.getmailspring.Mailspring"
	"com.github.IsmaelMartinez.teams_for_linux"
	"com.github.alexkdeveloper.desktop-files-creator"
	"com.github.huluti.Curtail"
	"com.github.marktext.marktext"
	"com.github.micahflee.torbrowser-launcher"
	"com.github.tchx84.Flatseal"
	"com.github.vikdevelop.photopea_app"
	"com.heroicgameslauncher.hgl"
	"com.jetbrains.WebStorm"
	"com.mattjakeman.ExtensionManager"
	"com.usebottles.bottles"
	"com.vscodium.codium"
	"com.wps.Office"
	"de.haeckerfelix.Shortwave"
	"de.shorsh.discord-screenaudio"
	"dev.geopjr.Collision"
	"dev.goats.xivlauncher"
	"hu.irl.cameractrls"
	"im.riot.Riot"
	"info.febvre.Komikku"
	"io.github.Foldex.AdwSteamGtk"
	"io.github.Hexchat"
	"io.github.giantpinkrobots.flatsweep"
	"io.github.mimbrero.WhatsAppDesktop"
	"io.github.nokse22.teleprompter"
	"io.github.seadve.Mousai"
	"io.github.spacingbat3.webcord"
	"io.github.thaunknown.miru"
	"io.gitlab.theevilskeleton.Upscaler"
	"io.gitlab.zehkira.Monophony"
	"it.mijorus.gearlever"
	"me.hyliu.fluentreader"
	"net.cozic.joplin_desktop"
	"net.davidotek.pupgui2"
	"net.mullvad.MullvadBrowser"
	"network.loki.Session"
	"nl.hjdskes.gcolor3"
	"org.audacityteam.Audacity"
	"org.briarproject.Briar"
	"org.eclipse.Javascript"
	"org.gustavoperedo.FontDownloader"
	"org.jdownloader.JDownloader"
	"org.kde.okteta"
	"org.kde.okular"
	"org.nickvision.tubeconverter"
	"org.onlyoffice.desktopeditors"
	"org.prismlauncher.PrismLauncher"
	"org.qbittorrent.qBittorrent"
	"org.signal.Signal"
	"org.tenacityaudio.Tenacity"
	)

	# Load installflatpaks.sh
	source "subscripts/installflatpaks.sh"
	
	# Export Array of required package names
	required_dependencies=(
	"build-essential"
	"alacritty"
	"balena-etcher"
	"bleachbit"
	"nala"
	"tldr"
	"unrar"
	"rar"
	"zip"
	"unzip"
	"mpv"
	"gcc"
	"manpages"
	"manpages-dev"
	"clang"
	"cpp"
	"coreutils"
	"curl"
	"dconf-editor"
	"dconf-cli"
	"ffmpeg"
	"g++"
	"meson"
	"ninja-build"
	"git"
	"python3"
	"python"
	"python-is-python3"
	"pip"
	"python3-pip"
	"python-pip"
	"glslang-tools"
	"ufw"
	"gufw"
	"gzip"
	"htop"
	"handbrake"
	"imwheel"
	"keepassxc"
	"lzip"
	"mkvtoolnix"
	"mkvtoolnix-gui"
	"neofetch"
	"ninja-build"
	"notepadqq"
	"npm"
	"openrgb"
	"powertop"
	"timeshift"
	"remmina"
	"wget"
	"whois"
	"yt-dlp"
	
	
	
	
	)

	# Execute missingpackages to check if packages are already installed
	source "subscripts/installdependencies.sh"
	installdependencies
}